### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by krt16s** [cerisara/Scrabble#1]
Hi,

the license file says it's GPLv2 or GPLv2+, you should add a note to the readme that this project is GPLv2+ (that is "GPLv2 and later"), because the support libraries are Apache2 licensed, which is incompatible with plain GPLv2.

Also, https://gitlab.com/fdroid/fdroiddata/merge_requests/938 says it's AGPL. Could you clarify this?

**Comment by cerisara** [comment]
Hi,

Thanks for pointing this out.
After analysis of the lib parts included, I've decided to move the whole code to licence AGPL to comply
with them. I've also added a header to these lib parts to reference the original copyright. It now also fits the fdroid metadata file.
