### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by unforgettableid** [cerisara/Scrabble#2]
Hi!

Where can I download binaries of your app?  I looked at https://github.com/cerisara/Scrabble/blob/master/README.md but didn't find any answer.

**Comment by cerisara** [comment]
Hi,

Sorry, I forgot to add the link to the apk:
https://f-droid.org/repository/browse/?fdfilter=Scrabble&fdid=fr.xtof54.scrabble

I've added it to the README.

Best,
xtof


2015-09-01 17:26 GMT+02:00 unforgettableid <notifications@github.com>:

**Comment by unforgettableid** [comment]
Thank you!  Merci!
